/**:
  ros__parameters:
    cmd_freq: 100.0  # freq platform publishes commands (Hz)
    info_freq: 10.0  # freq platform publishes info (Hz)
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    use_bypass: true
    tf_timeout_threshold: 0.05 # seconds (s)

